version: '3'
services:
  alluxio-master:
    container_name: alluxio-master
    image: mcorlion/alluxio:2.10.2
    shm_size: 4GB
    environment:
      ALLUXIO_JAVA_OPTS: "-Dalluxio.master.hostname=alluxio-master -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage -Dalluxio.user.file.writetype.default=THROUGH -Dalluxio.job.request.batch.size=1 -Dalluxio.master.metastore=HEAP -Dalluxio.job.worker.throttling=true"
    volumes:
      - /tmp/alluxio_ufs:/opt/alluxio/underFSStorage
    # ports:
    #   - 19999:19999
    #   - 19998:19998
    command: master
    networks:
      - alluxio-network    
  alluxio-worker-1:
    container_name: alluxio-worker-1
    image: mcorlion/alluxio:2.10.2
    shm_size: 8GB
    environment:
      ALLUXIO_JAVA_OPTS: "-Dalluxio.worker.ramdisk.size=4GB -Dalluxio.master.hostname=alluxio-master -Dalluxio.worker.hostname=alluxio-worker-1 -Dalluxio.user.file.writetype.default=THROUGH -Dalluxio.job.request.batch.size=1 -Dalluxio.master.metastore=HEAP -Dalluxio.job.worker.throttling=true"
    volumes:
      - /tmp/alluxio_ufs:/opt/alluxio/underFSStorage
    # ports:
    #   - 29999:29999
    #   - 30000:30000
    command: worker
    depends_on:
      - alluxio-master
    networks:
      - alluxio-network 
  alluxio-worker-2:
    container_name: alluxio-worker-2
    image: mcorlion/alluxio:2.10.2
    shm_size: 8GB
    environment:
      ALLUXIO_JAVA_OPTS: "-Dalluxio.worker.ramdisk.size=4GB -Dalluxio.master.hostname=alluxio-master -Dalluxio.worker.hostname=alluxio-worker-2 -Dalluxio.user.file.writetype.default=THROUGH -Dalluxio.job.request.batch.size=1 -Dalluxio.master.metastore=HEAP -Dalluxio.job.worker.throttling=true"
    volumes:
      - /tmp/alluxio_ufs:/opt/alluxio/underFSStorage
    # ports:
    #   - 29999:29999
    #   - 30000:30000    
    command: worker
    depends_on:
      - alluxio-master
    networks:
      - alluxio-network
networks:
  alluxio-network:
    external:
      name: alluxio_alluxio-network
# networks:
#   alluxio-network:
#     driver: bridge       