version: '2.1'
services:
  mysql:
    container_name: rpipedb
    image: docker.io/bitnami/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_CHARACTER_SET=utf8
      - MYSQL_COLLATE=utf8_general_ci
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - cp-network
networks:
  cp-network:
    external:
      name: cp-kafka_app-tier
volumes:
  mysql_data:
    driver: local
