version: '2'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: 'minio/minio:latest'
    container_name: minio_1
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - '/home/evan/minio/storage:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    networks:
      - app-tier